---
name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: "42 18 * * 3"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint
